version: "3"

services:
  spook:
    image: thebros35/spook
    #ports:
    #  - "4321:8000"
    #  - "9:9"
    volumes:
      - spookVolume:/app/db
    restart: unless-stopped
    network_mode: 'host'

volumes:
  spookVolume: